# Generated by Django 5.0.2 on 2024-03-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="count",
            new_name="quantity",
        ),
    ]
