# Generated by Django 5.0.2 on 2024-04-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_rename_count_orderitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
    ]
