# Generated by Django 5.0.2 on 2024-04-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_quantity_orderitem_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="count",
            new_name="quantity",
        ),
    ]
