# Generated by Django 5.0.2 on 2024-04-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_rename_count_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                max_length=250,
                verbose_name="Идентификатор связанного платежа",
            ),
        ),
    ]
