# Generated by Django 5.0.2 on 2024-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Действителен с")),
                ("valid_to", models.DateTimeField(verbose_name="Действителен по")),
                ("is_active", models.BooleanField(verbose_name="Активен")),
            ],
        ),
    ]
