# Generated by Django 5.0.2 on 2024-05-06 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.IntegerField(
                help_text="Percentage value (0 to 100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Процент скидки",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(verbose_name="Действителен с"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(verbose_name="Действителен по"),
        ),
    ]
